### ISSUE TITLE
Home Assistant error v0.107.7

### ISSUE THREAD

**Issue by franksimoes** [Villhellm/custom-sidebar#1]
Hi,

I installed the 'custom-card' correctly in Home Assistant v0.107.7.
Your card is ideal for what I need to use.
Put the only 'item:' that you can hide is the 'map'. Any of the others are ignored completely.

Thanks
--------------------------------------------------------------
order:
  - item: map
    hide: true
 - item: history
    hide: true
 - item: logbook
    hide: true
 - item: developer tools
    hide: true

**Comment by Villhellm** [comment]
I just updated to 0.107.7 to test this, it is still working fine for me. Can you please post your actual config in YAML using code blocks?

**Comment by Villhellm** [comment]
Sorry, didn't mean to close. I have a bad habit of doing that on accident

**Comment by franksimoes** [comment]
No problem, as for closing.
I'm using "custom_header", here is my list of 'resources / lovelace' and 'configuration.yaml'.



[configuration.yaml.txt](https://github.com/Villhellm/custom-sidebar/files/4416334/configuration.yaml.txt)
[resources.yaml.txt](https://github.com/Villhellm/custom-sidebar/files/4416335/resources.yaml.txt)



 






!

**Comment by Villhellm** [comment]
Please don't upload files, just post the YAML in a code block. Here is information on that if you need it https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks More to the point the things that you posted are irrelevant to the configuration for this plugin. I need the contents of your `sidebar-order.yaml`

**Comment by franksimoes** [comment]
Ok,... I'm sorry...

[ Configuration.yaml ]
```
homeassistant:
  # Name of the location where Home Assistant is running
  name: TRINITΨ
  # Location required to calculate the time the sun rises and sets
  latitude: -23.9529
  longitude: -46.3561
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo

   
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1  
  ip_ban_enabled: false
  login_attempts_threshold: 5
  base_url: https://iiotsensor.duckdns.org:8123
  

# Enables the frontend
frontend:
  themes: !include_dir_merge_named config/themes
  # controle sidebar --- 
  extra_module_url:
    - /local/custom-sidebar.js


# Enables configuration UI
config:

# habilitar menu hassio
hassio:


mqtt:
  broker: core-mosquitto
  #broker: 192.168.0.180  
  username: DEVuser
  password: DEVpw

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
#apitrinity_sytem - manutenção periódica do banco de dados.
recorder:
  purge_keep_days: 1
  purge_interval: 1
  exclude:
    entities:
      - sensor.time

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

#--sensor-- manter o tipo de inclusão de diretório
sensor: !include_dir_merge_list config/sensors/
#--switch-- manter o tipo de inclusão de diretório
switch: !include_dir_merge_list config/switches
#--switch-- manter o tipo de inclusão de diretório
light: !include_dir_merge_list config/lights/

#--input_number: manter o tipo de inclusão de diretório
# input_number: !include_dir_merge_named config/input_numbers/
#--input_select: manter o tipo de inclusão de diretório
input_select: !include_dir_merge_named config/input_selects/
#--input_text-- manter o tipo de inclusão por nome de  diretório
input_text: !include_dir_merge_named config/input_texts/

#--input_boolean-- manter o tipo de inclusão por nome de  diretório
#input_boolean: !include_dir_merge_named config/input_booleans/

lovelace:
  mode: yaml

system_health:

#--script-- manter o tipo de inclusão de diretório
script: !include_dir_merge_named config/scripts

# device_tracker: !include config/device_tracker.yaml

automation: !include_dir_merge_list config/automations/

shell_command: !include_dir_merge_named config/shell_command/

# Complementos em 24/05/2018
#--variable-- manter o tipo de inclusão de diretório
variable: !include_dir_merge_named config/variables/
```
----------------------------------------------------------------
[sidebar-order.yaml]
```
order:
  # Visão Geral === overview or lovelace ???
  - item: overview
    hide: true
  # Mapa    
  - item: map
    hide: true
  # Histórico
  - item: history
    hide: true
  # Log de Eventos
  - item: logbook
    hide: true
  # Ferramentas do desenvolvedor
  - item: developer tools
    hide: true
    
  # # ----- Future Testing ------  
  # # hassio /Supervisor
  # - item: hassio
    # bottom: true
  # # Configuration / config    
  # - item: config
    # bottom: true
```
---------------------------------------------------------------
[resources....]
```
  - url: /local/lovelace/card-tools.js
    type: module

  - url: /local/lovelace/button-card.js
    type: module

  - url: /local/lovelace/canvas-gauge-card.js
    type: module

  - url: /local/lovelace/gauge.min.js
    type: module

  - url: /local/lovelace/bignumber-card.js
    type: module

  - url: /local/lovelace/entity-attributes-card.js
    type: module

  - url: /local/lovelace/fold-entity-row.js
    type: module

  - url: /local/lovelace/vertical-stack-in-card.js
    type: module

  - url: /local/lovelace/vertical-style-card.js
    type: module

  - url: /local/lovelace/toggle-lock-entity-row.js
    type: module

  - url: /local/lovelace/state-switch.js
    type: module

  - url: /local/lovelace/gauge-card.js
    type: module

  - url: /local/lovelace/useful-markdown-card.js
    type: module

  - url: /local/lovelace/custom-header.js
    type: module

  - url: /local/lovelace/banner-card.js
    type: module

  - url: /local/lovelace/mini-graph-card-bundle.js
    type: module

  - url: /local/lovelace/dual-gauge-card.js
    type: module
```

tks!

**Comment by Villhellm** [comment]
When I use your `sidebar-order.yaml` in my instance everything hides as it should. What browser are you using and do you see any errors in the browser console? (you can open the browser console by pressing F12 on your keyboard in most browsers)

**Comment by franksimoes** [comment]
I did several tests, based on what you commented on and deepened the tests further. 
My intention is to be able to disable the following items: overview, map, history, logbook, developer, config and supervisor (hassio). 

The way that one of the "browsers" update, was a factor that I had not noticed, and affected the functioning. In tests with the new [sidebar-order.yaml], it came very close to the expected result, minus the options "overview" and "supervisor (hassio)".

**Tests with "Firefox Browser" 74.0 (64-bit): Results:**
- "FireFox" allows you to update in two ways:
--> Upgrading via "Ctrl + F5", it works 99% correctly.

![image](https://user-images.githubusercontent.com/15332011/78188272-51f89600-7446-11ea-886b-61aa7126fe26.png)

--> Updating via "Ctrl + R", the following items are ignored: "overview", "logbook", "history", "developer" and "supervisor (hassio)".


![image](https://user-images.githubusercontent.com/15332011/78189808-22975880-7449-11ea-93d9-4e402cf72a93.png)


**Considerations:**
- The settings have not been changed in all tests;
- There are no errors in "Console F12"; 
- When I activate Console mode, the "custom-sidebar" does not work correctly.
-------------------------------------------------------------------------------------
**Tests with "Google Chrome" Version 80.0.3987.149 (Version) 64 bits:**

-->Updating "Chrome" either via "Ctrl + F5" or "Ctrl + R" does not work, the behavior is the same.
 The following items are ignored: "overview", "logbook", "history", "developer" and "supervisor (hassio)".

- Note: Chrome mobile version, presents the same problem as the desktop version.

![image](https://user-images.githubusercontent.com/15332011/78191027-90448400-744b-11ea-8710-4f13af4d281f.png)

**Considerations:**
- The settings have not been changed in all tests;
- There are no errors in "Console F12"; 
- When I activate Console mode, the "custom-sidebar" does not work correctly.

--------------------------------------------------------------------------------------

Follows the current configuration [sidebar-order.yaml]:
```
order:
  # Visão Geral === overview or lovelace ???
  - item: overview
    hide: true
  # Mapa    
  - item: map
    hide: true
  # Histórico
  - item: history
    hide: true
  # Log de Eventos
  - item: logbook
    hide: true
  # Ferramentas do desenvolvedor
  - item: developer
    hide: true
  # Configuration / config    
  - item: config
    hide: true 
  # hassio /Supervisor
  - item: hassio
    hide: true
```

**Comment by Villhellm** [comment]
The problem seems to be the fact that you are not using English as your frontend language but you are trying to hide objects based on their English words. Use the Portuguese words that you see instead of their English translation. The reason Map was being hidden is because "Map" is in the word "Mapa".

**Comment by franksimoes** [comment]
I tested it in both languages, and considering upper and lower case, and the result has always been the same, don't hide it.

Both for "overview" => "Visão Geral" and for "hassio" => "Supervisor".

Now the other problem regarding updating browsers? From all that I described, it was clear that the only "browser" that works best is "Firefox" only when we press "Ctrl + F5". In "Chrome" it just doesn't work.

Tks!

**Comment by Villhellm** [comment]
I'm not sure why ctrl+F5 worked, I assume it renders in English on a cache clear before switching back to Portuguese when your profile fully loads. When I change my language to Portugeuse and match my config to the words are displayed everything is properly rearranged/hidden after refreshing the page (F5). It is not case sensitive, but it does function based on substrings. If it finds a match in any list item then the corresponding configuration will be applied.

**Comment by franksimoes** [comment]
I understand your explanation. I always take care when performing tests in "Browsers" cleaning caches to avoid recursive errors.

Sorry, if I wasn't clear, but these are two different problems that I tried to explain in a "post" only.

The problem with items that are not identified is one. In this case, only the items "overview" and "hassio", these are not at all.

The other problem is that even with the list as it is working, only in Firefox pressing Ctr + F5 can hide them.

Tks!

**Comment by Villhellm** [comment]
Can you post your current `sidebar-order.yaml` along with a screenshot?

**Comment by franksimoes** [comment]
Yeah!

Screenshot  in this comment:
https://github.com/Villhellm/custom-sidebar/issues/1#issuecomment-607515959

Configuration remains the same [sidebar-order.yaml]:
```
order:
  # Visão Geral === overview or lovelace ???
  - item: overview
    hide: true
  # Mapa    
  - item: map
    hide: true
  # Histórico
  - item: history
    hide: true
  # Log de Eventos
  - item: logbook
    hide: true
  # Ferramentas do desenvolvedor
  - item: developer
    hide: true
  # Configuration / config    
  - item: config
    hide: true 
  # hassio /Supervisor
  - item: hassio
    hide: true
```
Tks!

**Comment by Villhellm** [comment]
All of those entries are in English...

**Comment by franksimoes** [comment]
Note: remembering that the 'hassio' and 'overview' do not work.

**Comment by franksimoes** [comment]
Ok!

In this test, "hassio" works as "Supervisor". However the equivalent to the 'overview' as "Visão geral", I tested it with and without quotes and was not identified.

Funny that 'hassio' had tested right at the beginning of the tests and it didn't always work. And I had ruled out testing him as a "Supervisor" due to all the other items that had already worked were in English.

![image](https://user-images.githubusercontent.com/15332011/78300161-6eabd100-750d-11ea-971a-a3f34489a890.png)


```
order:
  # Visão Geral === overview or lovelace ???
  - item: Visão geral
    hide: true
  # Mapa    
  - item: map
    hide: true
  # Histórico
  - item: history
    hide: true
  # Log de Eventos
  - item: logbook
    hide: true
  # Ferramentas do desenvolvedor
  - item: developer
    hide: true
  # Configuration / config    
  - item: config
    hide: true 
  # hassio /Supervisor
  - item: Supervisor
    hide: true
```
Tks!

**Comment by franksimoes** [comment]
Hi, after the previous test and based on what you reinforced regarding languages ​​(English and Portuguese), I did the following test:
- declare in the configuration both languages;
- I kept: "map";
- I did not declare: "overview" in English;

Result: 
- everything worked perfectly well. In both browsers (Firefox and Chrome).

Suggestion:
- declare in the documentation that you must list the items in the native language and the configured language H.A.

```
order:
  # Visão Geral === overview or lovelace ???
  - item: Visão geral
    hide: true
  # Mapa    
  - item: map
    hide: true
  # Histórico
  - item: history
    hide: true
  - item: Histórico
    hide: true
  # Log de Eventos
  - item: logbook
    hide: true
  - item: Log de eventos
    hide: true    
  # Ferramentas do desenvolvedor
  - item: developer
    hide: false
  - item: Ferramentas do desenvolvedor
    hide: true
  # Configuration / config    
  - item: config
    hide: true 
  # hassio /Supervisor
  - item: Supervisor
    hide: true
```

Grateful for the support, your "card" is excellent for the result I expect in the interface I'm creating.

Thanks
