### ISSUE TITLE
Installing Custom Sidebar Module

### ISSUE THREAD

**Issue by NeWoKiKi** [Villhellm/custom-sidebar#13]
Hi,

Sorry, I don't think that's a real issue... maybe (or certainly ?) my bad but it' not working for me.
I searched for a way to contact you elsewhere but I didn't find so I'm raising this issue.

I installed HACS 1.4.1 on my Home Assistant 0.114.3, then I installed Custom Sidebar 0.1.7 using HACS.

I followed all instructions :
I added function in my configuration.yaml
```
frontend:
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js
```
I created my sidebar-order.yaml using exemple at first
```
order:
  - item: map
    hide: true
  - item: developer tools
    href: /developer-tools/state
  - item: overview
  - item: history
    bottom: true
  - item: logbook
    bottom: true
```

I restarted HA but nothing happen.

I can see a new line as Javascript in Resources
`/hacsfiles/custom-sidebar/custom-sidebar.js`

Maybe I missed something ? Is there anything else to do to get it work ?

Thanks by advance,
Regards,

**Comment by NeWoKiKi** [comment]
I tried to switch for English language but I have the same issue.
Nothing change, just like I didn't installed Custom Sidebar

**Comment by Villhellm** [comment]
Can you screenshot what your sidebar looks like and the page that loads when you go to `<your-ha-ip>/local/sidebar-order.yaml`?

**Comment by NeWoKiKi** [comment]
![image](https://user-images.githubusercontent.com/69678428/91845604-b6b85680-ec59-11ea-8a7d-a24e68d63ca4.png)

This is what my Sidebar looks like and when I go to your URL, it's downloading "sidebar-order.yaml" and this is what it contains : 
 
```
order:
  - item: map
    hide: true
  - item: developer tools
    href: /developer-tools/state
  - item: overview
  - item: history
    bottom: true
  - item: logbook
    bottom: true
```
