### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by u8915055** [Villhellm/custom-sidebar#22]
Hello,
I am running home assistant 0.115.2 (latest release) and am using custom-sidebar.  I have manually loaded it.  It seems to be working but I keep getting this error in the logs:

```
http://localhost:8123/local/custom-sidebar.js:62:22 Uncaught TypeError: Cannot read property 'length' of null
```

My config file is this:

```
order:
  - item: overview
    hide: false
  - item: dashboard
  - item: routines
  - item: history
  - item: sensors
  - item: layout
  - item: logbook
    hide: false
  - new_item: true
    item: Integrations
    href: /config/integrations
    icon: "mdi:server"
    bottom: true
  - item: developer tools
    bottom: true
  - item: configuration
    bottom: true
```

Again, it seems to be working but not sure why this message would be coming up.

Thank you very much.  Great module.
