### ISSUE TITLE
hidden: true dosen't work.

### ISSUE THREAD

**Issue by Cjdavidson** [Villhellm/custom-sidebar#3]
I have tried hide: true which is in your discription and hidden: true which is in your example. 

```
order:
  - item: notifications
  - item: overview
  - item: supervisor
  - item: hacs
  - item: configuration
  - item: developer tools
  - item: Deconz
    bottom: true
  - item: history
    hidden: true
  - item: map
    hide: true
  - item: logbook
    hide: true
```

And they both dont work any hints.
