### ISSUE TITLE
Sideside bar selections doubling up only on home screen

### ISSUE THREAD

**Issue by oneseventhree** [Villhellm/custom-sidebar#35]
Hi,

On https://xxx.xxx.x.xxx:8123/lovelace/default_view my side bar doubles up items and looks like:
<img width="250" alt="Screen Shot 2021-06-24 at 10 38 33 am" src="https://user-images.githubusercontent.com/15043282/123185034-5f30f300-d4d8-11eb-8724-0b9075c79f0e.png">

but on every other page (eg. https://xxx.xxx.x.xxx:8123/hassio/dashboard) it shows up right:
<img width="259" alt="Screen Shot 2021-06-24 at 10 38 20 am" src="https://user-images.githubusercontent.com/15043282/123185045-66f09780-d4d8-11eb-945c-6629bffea401.png">

What's causing this?

This is my sidebar-order.yaml:
```yaml
order:
  - item: Overview      # Overview
  - item: map
    hide: true
  - item: Logbook       # Logbook
  - item: history
    hide: true
  - item: HACS          # HACS
    href: /hacs/entry  
  - item: File Editor  # File Editor
    name: File Editor
    href: /core_configurator/dashboard
  - new_item: true
    item: Automations    # Automations
    href: /config/automation/dashboard
    icon: "mdi:robot"
  - new_item: true
    item: Scripts      # Scripts
    href: /config/script/dashboard
    icon: "mdi:script-text"
  - item: Media Browser # Media Browser
    hide: true
  - item: deCONZ          #deCONZ
    href: /core_deconz/dashboard
    bottom: true 
  - item: Developer Tools # Developer Tools
    href: /developer-tools/state
    bottom: true
  - item: Supervisor      # Supervisor
    href: /hassio/dashboard
    bottom: true
  - new_item: true
    item: Snapshots        # Snapshots
    href: /hassio/snapshots
    icon: "mdi:camera-plus"
    bottom: true
  - item: configuration   # Configuration
    href: /config/dashboard
    bottom: true
  - new_item: true
    item: Server Controls # Server Controls
    href: /config/server_control
    icon: "mdi:server"
    bottom: true  
```

Thanks!
