### ISSUE TITLE
Seems not working in 2021.6.6

### ISSUE THREAD

**Issue by pdwonline** [Villhellm/custom-sidebar#37]
I installed this and followed the guides. It seems not having any effect. Not any sign of live in the logs either. I have a Dutch version, so i used the exact text as the UI shows to me:

```
order:
  - item: Overzicht
  - item: Geschiedenis
  - item: Kaart
    hide: true
  - item: Mediabrowser
    hide: true

  - item: Ontwikkelhulpmiddelen
    href: /developer-tools/state
    bottom: true
     
  - item: Logboek
    bottom: true

  - item: Automatiseringen
    new_item: true
    href: config/automation/dashboard
    icon: "mdi:cog-sync"
    bottom: true

  - item: Instellingen
    bottom: true

  - item: HACS
    name: Extenties
    bottom: true
```

**Comment by benedikt-bartscher** [comment]
same here

**Comment by nathanmfast** [comment]
also same

**Comment by ChristophCaina** [comment]
Same here, latest HA Release as of 1st October...

```
order:
#  - item: map
#    hide: true
  - item: Karte
    hide: true
#  - item: logbook
#    hide: true
  - item: Logbuch
    hide: true
#  - item: history
#    hide: true
  - item: Verlauf
    hide: true
#  - item: mediabrowser
#    hide: true
  - item: Medien-Browser
    hide: true
  - item: HACS
    bottom: true
  - item: Grafana
    bottom: true
  - item: Node-RED
    bottom: true
  - item: Terminal
    bottom: true
  - item: Visual Studio Code
    bottom: true
  - item: HACS
    bottom: true
exceptions:
  - user: simone
#    base_order: true
    order:
#      - item: developer tools
#        hide: true
      - item: Entwicklungswerkzeuge
        hide: true
      - item: Supervisor
        hide: true
      - item: Visual Studio Code
        hide: true
      - item: Terminal
        hide: true
      - item: Node-RED
        hide: true
      - item: HACS
        hide: true
      - item: Grafana
        hide: true
```

// Done.
It seems that reloading Homeassistant did not work... instead, I've switched the browser-tab and after some time (reading some articles etc.) when I switched back to the HomeAssistant Tab, all Items had been reorganized as configured.

... maybe some cache? UI refresh interval with the newer version?
