### ISSUE TITLE
Exceptions not working

### ISSUE THREAD

**Issue by Imburr** [Villhellm/custom-sidebar#38]
I have tried every way to get exceptions working, and they simply wont. My goal here is:

- Have a user "tablet" showing only a few views
-  Have everyone else showing the same almost full sidebar

When I run this code, everyone get the "All" view, including tablet:

```
title: All
order:
  - item: map
    bottom: true
  - item: overview
  - item: history
    bottom: true
  - item: logbook
    bottom: true
  - item: supervisor
    bottom: true
  - item: Shopping List
    hide: true
  - item: Media Browser
    hide: true
  - item: Terminal
    hide: true
  - item: Server Controls
    bottom: true
  - item: HACS
    bottom: true
  - item: File editor
    bottom: true
  - item: Energy
    bottom: true
  - item: developer tools
    href: /developer-tools/state
    bottom: true
exceptions:
  - user: tablet
    order:
      - item: map
        hide: true
      - item: developer tools
        hide: true
      - item: File editor
        hide: true
      - item: HACS
        hide: true
      - item: Server Controls
        hide: true
```

If I change it to `  - not_user: tablet` nothing changes. In fact if I make any changes under exceptions, nothing is changed no matter the user, device, or order.

Any tips?
