### ISSUE TITLE
Feature Request: Custom Entries in Sidebar

### ISSUE THREAD

**Issue by david-kalbermatten** [Villhellm/custom-sidebar#6]
After the latest update of HA (Docker) the logs have been moved to the configuration page which sparked the idea that it'd be pretty nifty to be able to make custom entries with this integration:
```yaml
order:
  - item: custom
    name: "Logs"
    icon: mdi:note-text
    href: /config/logs
```

**Comment by Villhellm** [comment]
Yes this has actually been in my mental todo list for a while. Once I update to 0.112 I’ll start working on it 👍

**Comment by Villhellm** [comment]
0.1.3-beta release adds this ability. Please read the updated README for the correct syntax, it is slightly different than what you have suggested.

**Comment by david-kalbermatten** [comment]
First up, thanks you for implementing this feature 👍 
When I tried it, it didn't work...
```yaml
order:
  - item: overview
  - item: hacs
  - item: developer tools
    href: /developer-tools/state
  - item: map
    href: /config/logs
  - item: history
    bottom: true
  - item: logbook
    bottom: true
  - item: configuration
    bottom: true
  - new_item: true
    item: Server Controls
    href: /config/server_control
    icon: "mdi:server"
```
I reinstalled the latest beta version via HACS and restarted the Home Assistant after updating the config. However, it doesn't show up in the sidebar...

![image](https://user-images.githubusercontent.com/45201085/86618479-4672b900-bfb9-11ea-9076-ae134c24cc43.png)
