### ISSUE TITLE
Dashboards that are moved are automatically highlighted on first load

### ISSUE THREAD

**Issue by u8915055** [Villhellm/custom-sidebar#7]
I am using custom-sidebar with home assistant 0.112.5.  I have moved a couple of the dashboards, configuration and integrations to the bottom.  However when I first load up home assistant and log in, those two dashboards are highlighted for some reason in the sidebar.  The picture shows what I am referring to.  If I visit them and then leave them the highlight goes away.  I realize its not a huge problem but still inconsistent with im sure the way its supposed to work :)
Please let me know if you have any idea why this may be happening.
Here's my sidebar-order.yaml config:

```
order:
  - item: overview
    hide: true
  - item: dashboard
  - item: routines
  - item: history
  - item: sensors
  - new_item: true
    item: Integrations
    href: /config/integrations
    icon: "mdi:server"
    bottom: true
  - item: developer tools
    bottom: true
  - item: logbook
    hide: true
  - item: configuration
    bottom: true
```
Thanks very much.
Tom
<img width="274" alt="Screen Shot 2020-07-17 at 9 49 02 AM" src="https://user-images.githubusercontent.com/35235070/87811229-29d54d00-c813-11ea-9398-d2b57fc0acb9.png">
