### ISSUE TITLE
Edit order of Lovelace Dashboards 

### ISSUE THREAD

**Issue by bitwon** [Villhellm/custom-sidebar#8]
Would it

![chrome_JOKOyAQwgy](https://user-images.githubusercontent.com/60846394/87876312-a6b12400-c9d7-11ea-9940-6f56e6a509b5.png)

Will it be possible in the future to change the order of the Lovelace dashboards manually.

Currently the order is always like this:
- Default Dashboard
- alphabetically sorted order of all other dashboards (A-Z)

For "Einstellungen", I did a little trick with a "zero-width space"as prefix...

**Comment by Villhellm** [comment]
This is already possible with custom-sidebar. If it is not working, please share your sidebar-order.yaml file/

**Comment by bitwon** [comment]
order:
  - item: overview
  - item: Übersicht
  - item: lovelace-og
  - item: loveace-eg
  - item: lovelace-einstellungen

  - item: logbook
    bottom: true
  - item: Logbuch
    bottom: true
  - item: history
    bottom: true
  - item: Verlauf
    bottom: true
  - item: map
    bottom: true
  - item: Karte
    bottom: true
  - item: terminal
    bottom: true
  - item: core-ssh
    bottom: true
  - item: deconz
    bottom: true
  - item: developer
    bottom: true
  - item: Entwicklerwerzeuge
    bottom: true
  - item: hacs
    bottom: true
  - item: Supervisor
    bottom: true
  - item: file editor
    bottom: true
    icon: "mdi:file-document-edit"

![image](https://user-images.githubusercontent.com/60846394/88139781-b5265800-cbf0-11ea-8b0d-933ea00b339e.png)

**Comment by Villhellm** [comment]
You need to remove `lovelace-` from each of the entries. Like the docs say, you need to match what you see in the sidebar.

I'll push a release so you can specify "exact" string matches instead of just substrings because it's most likely going to break with items with such short names. 

Also you have a typo toward the bottom `Entwicklerwerzeuge`, which is why it's not working there

**Comment by bitwon** [comment]
@Villhellm Thanks for supporting. I updated to version 1.4 and adapted the config for testing to the following:

```yaml
order:
  - item: EG
    exact: true
  - item: overview
    exact: true
  - item: Übersicht
    exact: true
  - item: OG
    exact: true
  - item: Einstellungen
    exact: true


# Bottom
  - item: logbook
    bottom: true
  - item: Logbuch
    bottom: true
  - item: history
    bottom: true
  - item: Verlauf
    bottom: true
  - item: map
    bottom: true
  - item: Karte
    bottom: true
  - item: terminal
    bottom: true
  - item: core-ssh
    bottom: true
  - item: deconz
    bottom: true
  - item: developer
    bottom: true
  - item: Entwicklerwerkzeuge
    bottom: true
  - item: hacs
    bottom: true
  - item: Supervisor
    bottom: true
  - item: file editor
    bottom: true
    icon: "mdi:file-document-edit"
```

But I'm not getting what I expected:
![image](https://user-images.githubusercontent.com/60846394/88368063-87c2e100-cd8d-11ea-9451-785981b2d1fc.png)

Maybe you see the problem 🙈
