### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by IanAdd** [Villhellm/custom-sidebar#9]
Could you add a name: option to allow the item: found to be displayed with a different name.
For example
I have phpMyAdmin showing in my sidebar because I use Mariadb. I would like the sidebar to show 'MariaDb' instead of 'phpMyAdmin'. So I imagine the entry might be (if this was achievable)
```
order:
  - item: php
    name: MariaDb
    bottom: true
```
